before_script:
  - REPO="$(echo $TRAVIS_REPO_SLUG | cut -d'/' -f2)"

script: 
  - echo Generating zip file for plugin $REPO
  - mkdir $REPO
  - rsync -Rr . ./$REPO/
  - rm -rf ./$REPO/$REPO ./$REPO/.git
  - zip -r $TRAVIS_BUILD_DIR/$REPO.zip $REPO
  - unzip -l $REPO.zip

deploy:
  provider: releases
  api_key:
    secure: iLMCIZmIkTHMdOEI9TqTh3Afq/Y6U+cfo8rq+zDP4TUAJCxKaJ/q4Zv9OoDy6KHH6hr55gajWoQB3oMBuITAVgIc1QBafNOb3G+zUs/PRKhyToMEjqnetbnMy/tBIBTOfJfaV+FGpA8IGGKe4FujrJu5bnrF9czq9LYZbKcmyce6sP8N4qme+FQCZmVmY44mphRw23WB/kn8MFaMM5/6faWdT/xmhmZjSkY+daFLw3lnBYF/uSQyHG+dNT9B/qbm/RM9JE5CoKe//x7R1EUE0FbLZE5Z9i9qUwfdvDKYHuEcGtELVQSOy3Mev9TE4oq/XVEXnSWe3jAm2WxV/oUkOnj9nFb1GArjU4Er34Fe1U7ikSB8uGHrD6flGVPO4xe5axyBpqwqipOiJ/m344/oGvVyrF9YLtMCGvuWA4jAxysZd/qmtR3P88jm88LQSHeUcRtGYDIVPFgQH4aesSO7CsVygJaqHdxZX9pAVPsPydsqU23VYWgZkVHdomsErOBVuuukJ8tqTCWvDqA8PnrAkhmz2GpQHOzllNlwg4WIblg/Tw/1kpMCoe3tgUF743aPXq0INUVru2cWzbk01sdN0hWDyt8XX6zGrxFsNghbFOrzFKThxoMuz5370sstd4OhkRG74LVLuXdzKS/PmFM7E0gJa8IiurEBYN664CA9nEQ=
  file: "$TRAVIS_BUILD_DIR/$REPO.zip"
  skip_cleanup: true
  on:
    tags: true